CREATE DATABASE yeticave
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE lot(
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title CHAR(128) NOT NULL UNIQUE,
    description CHAR(255),
    img_url CHAR(255) NOT NULL,
    price_start FLOAT NOT NULL,
    end_at DATETIME,
    bet_step INT,
    category_id INT NOT NULL REFERENCES category(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    user_id INT NOT NULL REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    winner_user_id INT REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE category(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title CHAR(128) NOT NULL UNIQUE
);

CREATE TABLE user(
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email CHAR(128) NOT NULL UNIQUE,
    name CHAR(128) NOT NULL,
    password CHAR(64) NOT NULL,
    avatar_url CHAR(255) NOT NULL,
    contacts TEXT
);

CREATE TABLE bet(
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bet_value INT,
    user_id INT NOT NULL references user(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    lot_id INT NOT NULL references lot(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
